language: ruby
rvm:
  - 2.2.3
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
before_script:
  - psql -c 'create database workshops_test;' -U postgres
addons:
  postgresql: '9.3'
